name: Deploy to GitHub pages

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - run: npm install -g pnpm gh-pages
      - run: pnpm i --no-frozen-lockfile
      - run: pnpm run build
      - run: npx gh-pages -d dist -t true