name: Deploy to GitHub pages

on:
 push:
    branches:
      - main
 pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install & Build
        uses: npm install -g pnpm && pnpm i --no-frozen-lockfile && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: dist